# python base image in the container from Docker Hub
FROM python:3.8.12-buster

# copy files to the /app folder in the container
COPY create.py /create.py
COPY requirements.txt /requirements.txt

RUN pip install -r /requirements.txt

EXPOSE 8502

CMD ["python","-u","create.py","--server.port", "8502"]
